services:
  - type: web
    name: foodie-backend
    env: node
    repo: https://github.com/anshumanat/Food-ordering-platform
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URL
        value: your_mongo_connection_url

  - type: web
    name: foodie-frontend
    env: static
    repo: https://github.com/anshumanat/Food-ordering-platform
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
